spring.application.name=proyec_herramientas

spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.username=admin
spring.mongodb.password=123
spring.mongodb.authentication-database=admin
spring.mongodb.database=proyecto
